# Generated by Django 2.0.5 on 2018-09-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
