# Generated by Django 2.0.5 on 2018-10-04 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181004_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 23, 29, 4, 608442)),
        ),
    ]
